# This folder is cached between builds for faster runs
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/

stages:
  - build
  - test

build:
  stage: build
  script:
    - echo 'Hello, $GITLAB_USER_LOGIN!'
    - echo 'Commit branch, $CI_COMMIT_BRANCH'
    - echo 'build'
    # - mkdir
    # - touch build/info.txt
    - npm install
    - npm run build

  # artifacts:
  #     paths:
  #       - dist/

test:
  stage: test
  script:
    - echo 'test'
    # - mkdir
    # - test -f 'build/info.txt'
