# This folder is cached between builds for faster runs
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  key: node_deps
  paths: 
    - node_modules/

stages:
  - build
  # - lint
  - test

build:
  stage: build
  image: node:latest
  script:
    - echo 'Hello, $GITLAB_USER_LOGIN!'
    - echo 'Commit branch, $CI_COMMIT_BRANCH'
    - echo 'build'
    - mkdir dist
    - touch dist/hello.tkt
    - npm install
    - npm run build

  artifacts:
    paths:
      - dist/

# lint:
#   stage: lint
#   image: node:latest
#   script:
#     - echo 'Linting time'
#     - npm run lint

test:
  stage: test
  script:
    - echo 'test'
    - test -f 'dist/hello.tkt'
