stages:
  - build
  - test

build:
  stage: build
  script:
    - echo 'build'
    - mkdir
    - touch build/info.txt

test:
  stage: test
  script:
    - echo 'test'
    - mkdir
    - test -f 'build/info.txt'